added nord theme
spicetify/spicetify-docs pull request #62
Opened 2022-10-12 08:16 UTC by Tetrax-10

@theRealPadster can you change this image to Nord theme. becuase that image looks like a default spotify.
![image](https://user-images.githubusercontent.com/75513645/195288275-6621308b-14dc-420c-95e9-35b6a0bb51ca.png)

2022-10-12 12:46 UTC, theRealPadster commented
I believe that first screenshot is an old version of Comfy? It's got the gradient play bar. But feel free to change it, or add a screenshot or two from Nord into the carousel. The files are all in this repo, so you can do in this same PR

2022-10-12 12:46 UTC, theRealPadster requested changes

2022-10-12 12:46 UTC, theRealPadster commented on docs/advanced-usage/themes.md
> +5. [Tetrax-10/Nord-Spotify](https://github.com/Tetrax-10/Nord-Spotify)
Can you add the "add your theme here" entry as number 6? We don't want to remove it.

2022-10-12 13:06 UTC, Tetrax-10 commented
> 

i know all those images are there in the repo but i dont know to take a ss with that rounded corner with faded bg. all images should be even so its better you take a ss and commit it

2022-10-13 04:03 UTC, theRealPadster commented
> i know all those images are there in the repo but i dont know to take a ss with that rounded corner with faded bg. all images should be even so its better you take a ss and commit it

Oh, right, I forgot I made them that way. That's how macos saves them. I'll see what I can do.

2022-10-13 21:41 UTC, theRealPadster commented
Hey @afonsojramos , could you replace the themes screenshot with something that doesn't look so stock? (It looks like your account.) I was going to but my screen isn't big enough to keep the same resolution. 
![image](https://user-images.githubusercontent.com/1565883/195716121-e44e9d6d-a058-4511-af5f-b4339621127b.png)

2022-10-13 21:44 UTC, theRealPadster approved these changes
Looks good to me. Feel free to update that themes image, but can merge as far as I'm concerned.

2022-10-14 06:31 UTC, Tetrax-10 commented
Looks good to me too.

> Hey @afonsojramos , could you replace the themes screenshot with something that doesn't look so stock? (It looks like your account.) I was going to but my screen isn't big enough to keep the same resolution. ![image](https://user-images.githubusercontent.com/1565883/195716121-e44e9d6d-a058-4511-af5f-b4339621127b.png)

I Recommend Bloom/ziro/sleek

2022-10-14 18:38 UTC, afonsojramos commented
@theRealPadster It's fine if it isn't the same res! Actually it would be better if it was a smaller res!

2022-10-14 20:38 UTC, theRealPadster commented
> @theRealPadster It's fine if it isn't the same res! Actually it would be better if it was a smaller res!

Well I just meant so those three in that block are the same size. Should we just redo them all then?

2022-10-24 14:19 UTC, theRealPadster commented
I don't feel like redoing all those screenshots right now, so I'm gonna merge this in, and you can make another issue/PR about updating them if it really matters.

2022-10-24 14:20 UTC, merged